# Generated by Django 4.2.2 on 2023-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='projects/'),
        ),
    ]
